/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DropshippingRouteImport } from './routes/dropshipping'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AdminAdsRouteImport } from './routes/_admin/ads'
import { Route as AdminProductsRouteImport } from './routes/_admin/products'
import { Route as AdminRevenueRouteImport } from './routes/_admin/revenue'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiGeoRouteImport } from './routes/api.geo'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalMentionsRouteImport } from './routes/legal.mentions'
import { Route as PaiementRetourRouteImport } from './routes/paiement.retour'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as VendeurIdRouteImport } from './routes/vendeur.$id'
import { Route as AuthenticatedDashboardNewRouteImport } from './routes/_authenticated/dashboard.new'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as ApiAiEnrichRouteImport } from './routes/api.ai.enrich'
import { Route as ApiAiStatusRouteImport } from './routes/api.ai.status'
import { Route as ApiJobsBoostDailyRouteImport } from './routes/api.jobs.boost-daily'
import { Route as ApiPayCheckoutRouteImport } from './routes/api.pay.checkout'
import { Route as ApiPayReconcileRouteImport } from './routes/api.pay.reconcile'
import { Route as ApiPayStripeCheckRouteImport } from './routes/api.pay.stripe-check'
import { Route as AuthenticatedDashboardEditIdRouteImport } from './routes/_authenticated/dashboard.edit.$id'
import { Route as ApiPayWebhookProviderRouteImport } from './routes/api.pay.webhook.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DropshippingRoute = DropshippingRouteImport.update({
  id: '/dropshipping',
  path: '/dropshipping',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiGeoRoute = ApiGeoRouteImport.update({
  id: '/api/geo',
  path: '/api/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => LegalRoute,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => LegalRoute,
} as any)
const PaiementRetourRoute = PaiementRetourRouteImport.update({
  id: '/paiement/retour',
  path: '/paiement/retour',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendeurIdRoute = VendeurIdRouteImport.update({
  id: '/vendeur/$id',
  path: '/vendeur/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardNewRoute =
  AuthenticatedDashboardNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const ApiAiEnrichRoute = ApiAiEnrichRouteImport.update({
  id: '/api/ai/enrich',
  path: '/api/ai/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsBoostDailyRoute = ApiJobsBoostDailyRouteImport.update({
  id: '/api/jobs/boost-daily',
  path: '/api/jobs/boost-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayCheckoutRoute = ApiPayCheckoutRouteImport.update({
  id: '/api/pay/checkout',
  path: '/api/pay/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayReconcileRoute = ApiPayReconcileRouteImport.update({
  id: '/api/pay/reconcile',
  path: '/api/pay/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayStripeCheckRoute = ApiPayStripeCheckRouteImport.update({
  id: '/api/pay/stripe-check',
  path: '/api/pay/stripe-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardEditIdRoute =
  AuthenticatedDashboardEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPayWebhookProviderRoute = ApiPayWebhookProviderRouteImport.update({
  id: '/api/pay/webhook/$provider',
  path: '/api/pay/webhook/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dropshipping': typeof DropshippingRoute
  '/legal': typeof LegalRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AdminAdminRoute
  '/ads': typeof AdminAdsRoute
  '/products': typeof AdminProductsRoute
  '/revenue': typeof AdminRevenueRoute
  '/users': typeof AdminUsersRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/api/geo': typeof ApiGeoRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/paiement/retour': typeof PaiementRetourRoute
  '/product/$id': typeof ProductIdRoute
  '/vendeur/$id': typeof VendeurIdRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/api/ai/enrich': typeof ApiAiEnrichRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/jobs/boost-daily': typeof ApiJobsBoostDailyRoute
  '/api/pay/checkout': typeof ApiPayCheckoutRoute
  '/api/pay/reconcile': typeof ApiPayReconcileRoute
  '/api/pay/stripe-check': typeof ApiPayStripeCheckRoute
  '/dashboard/edit/$id': typeof AuthenticatedDashboardEditIdRoute
  '/api/pay/webhook/$provider': typeof ApiPayWebhookProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dropshipping': typeof DropshippingRoute
  '/legal': typeof LegalRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AdminAdminRoute
  '/ads': typeof AdminAdsRoute
  '/products': typeof AdminProductsRoute
  '/revenue': typeof AdminRevenueRoute
  '/users': typeof AdminUsersRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/api/geo': typeof ApiGeoRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/paiement/retour': typeof PaiementRetourRoute
  '/product/$id': typeof ProductIdRoute
  '/vendeur/$id': typeof VendeurIdRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/api/ai/enrich': typeof ApiAiEnrichRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/jobs/boost-daily': typeof ApiJobsBoostDailyRoute
  '/api/pay/checkout': typeof ApiPayCheckoutRoute
  '/api/pay/reconcile': typeof ApiPayReconcileRoute
  '/api/pay/stripe-check': typeof ApiPayStripeCheckRoute
  '/dashboard/edit/$id': typeof AuthenticatedDashboardEditIdRoute
  '/api/pay/webhook/$provider': typeof ApiPayWebhookProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dropshipping': typeof DropshippingRoute
  '/legal': typeof LegalRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_admin/ads': typeof AdminAdsRoute
  '/_admin/products': typeof AdminProductsRoute
  '/_admin/revenue': typeof AdminRevenueRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/api/geo': typeof ApiGeoRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/paiement/retour': typeof PaiementRetourRoute
  '/product/$id': typeof ProductIdRoute
  '/vendeur/$id': typeof VendeurIdRoute
  '/_authenticated/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/api/ai/enrich': typeof ApiAiEnrichRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/jobs/boost-daily': typeof ApiJobsBoostDailyRoute
  '/api/pay/checkout': typeof ApiPayCheckoutRoute
  '/api/pay/reconcile': typeof ApiPayReconcileRoute
  '/api/pay/stripe-check': typeof ApiPayStripeCheckRoute
  '/_authenticated/dashboard/edit/$id': typeof AuthenticatedDashboardEditIdRoute
  '/api/pay/webhook/$provider': typeof ApiPayWebhookProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/dropshipping'
    | '/legal'
    | '/tarifs'
    | '/admin'
    | '/ads'
    | '/products'
    | '/revenue'
    | '/users'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/api/geo'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/paiement/retour'
    | '/product/$id'
    | '/vendeur/$id'
    | '/dashboard/new'
    | '/profile/edit'
    | '/api/ai/enrich'
    | '/api/ai/status'
    | '/api/jobs/boost-daily'
    | '/api/pay/checkout'
    | '/api/pay/reconcile'
    | '/api/pay/stripe-check'
    | '/dashboard/edit/$id'
    | '/api/pay/webhook/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/dropshipping'
    | '/legal'
    | '/tarifs'
    | '/admin'
    | '/ads'
    | '/products'
    | '/revenue'
    | '/users'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/api/geo'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/paiement/retour'
    | '/product/$id'
    | '/vendeur/$id'
    | '/dashboard/new'
    | '/profile/edit'
    | '/api/ai/enrich'
    | '/api/ai/status'
    | '/api/jobs/boost-daily'
    | '/api/pay/checkout'
    | '/api/pay/reconcile'
    | '/api/pay/stripe-check'
    | '/dashboard/edit/$id'
    | '/api/pay/webhook/$provider'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/dropshipping'
    | '/legal'
    | '/tarifs'
    | '/_admin/admin'
    | '/_admin/ads'
    | '/_admin/products'
    | '/_admin/revenue'
    | '/_admin/users'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/profile'
    | '/api/geo'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/paiement/retour'
    | '/product/$id'
    | '/vendeur/$id'
    | '/_authenticated/dashboard/new'
    | '/_authenticated/profile/edit'
    | '/api/ai/enrich'
    | '/api/ai/status'
    | '/api/jobs/boost-daily'
    | '/api/pay/checkout'
    | '/api/pay/reconcile'
    | '/api/pay/stripe-check'
    | '/_authenticated/dashboard/edit/$id'
    | '/api/pay/webhook/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DropshippingRoute: typeof DropshippingRoute
  LegalRoute: typeof LegalRouteWithChildren
  TarifsRoute: typeof TarifsRoute
  ApiGeoRoute: typeof ApiGeoRoute
  PaiementRetourRoute: typeof PaiementRetourRoute
  ProductIdRoute: typeof ProductIdRoute
  VendeurIdRoute: typeof VendeurIdRoute
  ApiAiEnrichRoute: typeof ApiAiEnrichRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiJobsBoostDailyRoute: typeof ApiJobsBoostDailyRoute
  ApiPayCheckoutRoute: typeof ApiPayCheckoutRoute
  ApiPayReconcileRoute: typeof ApiPayReconcileRoute
  ApiPayStripeCheckRoute: typeof ApiPayStripeCheckRoute
  ApiPayWebhookProviderRoute: typeof ApiPayWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropshipping': {
      id: '/dropshipping'
      path: '/dropshipping'
      fullPath: '/dropshipping'
      preLoaderRoute: typeof DropshippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ads': {
      id: '/_admin/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/revenue': {
      id: '/_admin/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/geo': {
      id: '/api/geo'
      path: '/api/geo'
      fullPath: '/api/geo'
      preLoaderRoute: typeof ApiGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/paiement/retour': {
      id: '/paiement/retour'
      path: '/paiement/retour'
      fullPath: '/paiement/retour'
      preLoaderRoute: typeof PaiementRetourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendeur/$id': {
      id: '/vendeur/$id'
      path: '/vendeur/$id'
      fullPath: '/vendeur/$id'
      preLoaderRoute: typeof VendeurIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/new': {
      id: '/_authenticated/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof AuthenticatedDashboardNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/api/ai/enrich': {
      id: '/api/ai/enrich'
      path: '/api/ai/enrich'
      fullPath: '/api/ai/enrich'
      preLoaderRoute: typeof ApiAiEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/boost-daily': {
      id: '/api/jobs/boost-daily'
      path: '/api/jobs/boost-daily'
      fullPath: '/api/jobs/boost-daily'
      preLoaderRoute: typeof ApiJobsBoostDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/checkout': {
      id: '/api/pay/checkout'
      path: '/api/pay/checkout'
      fullPath: '/api/pay/checkout'
      preLoaderRoute: typeof ApiPayCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/reconcile': {
      id: '/api/pay/reconcile'
      path: '/api/pay/reconcile'
      fullPath: '/api/pay/reconcile'
      preLoaderRoute: typeof ApiPayReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/stripe-check': {
      id: '/api/pay/stripe-check'
      path: '/api/pay/stripe-check'
      fullPath: '/api/pay/stripe-check'
      preLoaderRoute: typeof ApiPayStripeCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/edit/$id': {
      id: '/_authenticated/dashboard/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof AuthenticatedDashboardEditIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/pay/webhook/$provider': {
      id: '/api/pay/webhook/$provider'
      path: '/api/pay/webhook/$provider'
      fullPath: '/api/pay/webhook/$provider'
      preLoaderRoute: typeof ApiPayWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardNewRoute: typeof AuthenticatedDashboardNewRoute
  AuthenticatedDashboardEditIdRoute: typeof AuthenticatedDashboardEditIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardNewRoute: AuthenticatedDashboardNewRoute,
    AuthenticatedDashboardEditIdRoute: AuthenticatedDashboardEditIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LegalRouteChildren {
  LegalCguRoute: typeof LegalCguRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCguRoute: LegalCguRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsRoute: LegalMentionsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DropshippingRoute: DropshippingRoute,
  LegalRoute: LegalRouteWithChildren,
  TarifsRoute: TarifsRoute,
  ApiGeoRoute: ApiGeoRoute,
  PaiementRetourRoute: PaiementRetourRoute,
  ProductIdRoute: ProductIdRoute,
  VendeurIdRoute: VendeurIdRoute,
  ApiAiEnrichRoute: ApiAiEnrichRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiJobsBoostDailyRoute: ApiJobsBoostDailyRoute,
  ApiPayCheckoutRoute: ApiPayCheckoutRoute,
  ApiPayReconcileRoute: ApiPayReconcileRoute,
  ApiPayStripeCheckRoute: ApiPayStripeCheckRoute,
  ApiPayWebhookProviderRoute: ApiPayWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
